import { Container, Header } from "@/components/shared";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function ChekoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className=" min-h-screen ">
      <Container>
        <Header hasSearch={false} hasCart={false} />
        {children}
      </Container>
    </main>
  );
}
